### ISSUE TITLE
Add css and minified css to npm package

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#21]
**Description**
We should add css and minified css to the `@unimeta/meta` npm package for more compatibility.

**Tasks**
- [ ] Review how [`Bootstrap`](https://github.com/twbs/bootstrap/blob/v4-dev/package.json) handles their `package.json` scripting.
- [ ] Create a `dist/` directory in root
- [ ] Create a `css/` directory inside the `./dist` directory.
- [ ] Create new script under `scripts` in `package.json` that;
  - [ ] Compiles `node_modules/bootstrap/scss/bootstrap.scss` and `src/scss/meta.scss` that saves and replaces;
    - [ ] `meta.css` and places it in `dist/css`.
    - [ ] and minifies `meta.css` and places it in `dist/css`.
- [ ] Set `files` to be included into the published npm package.

**Structure**
```
meta
├── dist/
│  └── css/
|     └── meta.css
|     └── meta.css.map
|     └── meta.min.css
|     └── meta.min.css.map
├── LICENSE
├── package.json
├── README.md
└── scss/
   └── meta.scss
```

**Comment by guylepage3** [comment]
Review [Bootstrap's `package.json`](https://github.com/twbs/bootstrap/blob/v4-dev/package.json) file to see how they compile, minify and replace their css for publishing in their `dist` directory.

More specifically, review the following:

```
"css": "npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*",
    "css-main": "npm-run-all --parallel css-lint css-compile --sequential css-prefix css-minify css-copy",
    "css-docs": "npm-run-all --parallel css-lint-docs css-compile-docs --sequential css-prefix-docs css-minify-docs",
    "css-compile": "node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css",
```

**Comment by guylepage3** [comment]
Deprecated. We are not doing this and letting the end user compile the sass. If someone requests a css minified version we'll add it to the build script.
