### ISSUE TITLE
Build out a very quick  Meta Docs site for users

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#26]
**Description**
Build out a very quick  Meta Docs site for users. We can simply take the layout from http://universe.engineering/roadmap and apply a very simple `.jumbotron` to the top with a button to [NPM page](https://www.npmjs.com/package/@universelabs/meta) and another to the [Meta UI Design System (located in Sketch Cloud)](https://sketch.cloud/s/Plnvv)

Let's not focus on the content so much as just placing content for now. We'll pull in @aseoconnor to handle a quick iteration of the content once it's in place.

**Tasks**
- [x] #53 Build out grid (non-responsive).
- [x] Build out home view.
- [x] Build out Typography (default).
- [x] Build out Typography Editorial.
- [x] Add grid to all pages.
- [x] Build Navbar component.
  - [x] Home
  - [x] Typography (Default)
  - [x] Typography Editorial
- [x] Jumbotron.
  - [ ] Button - [NPM page](https://www.npmjs.com/package/@universelabs/meta)
  - [ ] Button - [Meta UI Design System (located in Sketch Cloud)](https://sketch.cloud/s/Plnvv)
  - [ ] Version number in small type below the buttons.
- [x] Description of Meta.

**Comment by guylepage3** [comment]
Pulled in from https://github.com/orgs/universelabs/projects/1#card-18812934

**Comment by guylepage3** [comment]
Here's the new Headline and Lead copy for the Jumbotron... https://github.com/universelabs/meta/issues/47#issuecomment-473394099
