### ISSUE TITLE
Add and define blockquote & blockquote-footer

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#29]
**Description**
Add and define values `blockquote` and `blockquote-footer`.

Reference: 
- https://github.com/universelabs/meta/issues/13
- https://getbootstrap.com/docs/4.1/content/typography/#blockquotes

A summary of the issue If suitable, include the tasks required for the issue.

**Tasks**
- [x] Define values for `blockquote`.
- [x] Define values for `blockquote-footer`.
- [x] Add values for `blockquote` to Meta.
- [x] Add values for `blockquote-footer` to Meta.
- [x] Test with all alignments.
- [x] Define values for a "medium" blockquote.
- [x] Define values for a "medium" blockquote footer.
- [x] Add values for a "medium" blockquote to Meta.
- [x] Add values for a "medium" blockquote footer to Meta.
- [x] Test with all alignments.
- [x] Define values for a "large" blockquote.
- [x] Define values for a "large" blockquote footer.
- [x] Add values for a "large" blockquote to Meta.
- [x] Add values for a "large" blockquote footer to Meta.
- [x] Test with all alignments.
- [x] Define values for a "primary, medium & large" mobile blockquote.
- [x] Define values for a "primary, medium & large" mobile blockquote footer.
  - Need to refactor responsive type scaling using sass maps. See #31 below.
  - Need to update all values in typography definition (Desktop).
- [ ] Add values for a "primary, medium & large" mobile blockquote to Meta.
- [ ] Add values for a "primary, medium & large" mobile blockquote footer to Meta.
- [ ] Test with all alignments.

Noticed that we were not using Sass mapping for simpler less code.
- [x] [#31 Refactor responsive type scaling using sass maps](https://github.com/universelabs/meta/issues/31)

**Comment by guylepage3** [comment]
| **SMALL SET**   | **(Base font 16px)**         |                        |                   |
| :-------------- | :--------------------------- | :--------------------- | :---------------- |
|                 |                              |                        |                   |
|                 |                              |                        |                   |
| **Mobile**      | **1rem == 16px**             |                        |                   |
| **1.125 ratio** |                              |                        |                   |
|                 | **Item**                     | **Font size**          | **Rounded**       |
|                 | `.lead-lg` // Custom         | 1.5rem (24px)          | 1.5rem (24px)    |
|                 | `.lead`                      | 1.125rem (18px)        | 1.125rem (18px)    |
|                 | `.blockquote`                |                        | -                 |
|                 | `.blockquote-footer`         |                        | -                 |
|                 |                              |                        |                   |
|                 |                              |                        |                   |
| **Desktop**     | **1rem == 17px (1.0625rem)** |                        |                   |
| **Custom**   |                              |                        |0.05882352                   |
|                 | **Item**                     | **Font size**          | **Rounded**       |
|                 | `.lead-lg` // Custom         | 1.6471rem (28px)         | 1.64705856rem (28px)    |
|                 | `.lead`                      | 1.2353rem (21px)       | 1.23529392rem (21px)    |
|                 | `.blockquote`                |                        | -                 |
|                 | `.blockquote-footer`         |                        | -                 |
| **Desktop**     | **1rem == 17px (1.0625rem)** |                        |                   |
| **1.2 ratio**   |                              |                        |                   |
|                 | **Item**                     | **Font size**          | **Rounded**       |
|                 | `.lead-lg` // Custom         | 1.75rem (29.75px)         | 1.7647056rem (30px)    |
|                 | `.lead`                      | 1.3125rem (22.3125px)       | 1.29411744rem (22px)    |
|                 | `.blockquote`                |                        | -                 |
|                 | `.blockquote-footer`         |                        | -                 |

**Comment by guylepage3** [comment]
<img width="1273" alt="screenshot 2018-12-18 18 55 49" src="https://user-images.githubusercontent.com/1711854/50190239-8b130280-02f6-11e9-8013-99732627921c.png">

**Comment by guylepage3** [comment]
Complete.

<img width="1145" alt="screenshot 2018-12-26 15 15 35" src="https://user-images.githubusercontent.com/1711854/50456347-b793d380-0921-11e9-96a0-d447744eb2c9.png">
<img width="1146" alt="screenshot 2018-12-26 15 15 46" src="https://user-images.githubusercontent.com/1711854/50456348-b793d380-0921-11e9-9932-cf501dda1603.png">
<img width="1144" alt="screenshot 2018-12-26 15 16 11" src="https://user-images.githubusercontent.com/1711854/50456349-b793d380-0921-11e9-837b-65a992f49d77.png">
