### ISSUE TITLE
Refactor responsive type scaling using sass maps

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#31]
**Description**
Refactor sm breakpoint styles in css to be sass maps for simplicity.

References
- [How Bootstrap Sets Up Typography by Default](https://www.sitepoint.com/build-responsive-type-scale-bootstrap/)
  - https://codepen.io/guylepage3/pen/qLRGGW?editors=0100

**Tasks**
- [x] Setup type scale map for quick changes and experiments
- [x] Build a function to check if the scale is valid for use
- [x] Build two mixins to allow us the flexibility of adjusting the font sizes at any given time.

**Elements that need refactoring**
- [x] `h1`, `h2`, `h3`, `h4`, `h5`, `h6` elements and `.h1`, `.h2`, `.h3`, `.h4`, `.h5`, `.h6` classes.
- [x] `.display-*` 1-4 heading classes.
- [x] `margin-top`
- [x] `line-height`

**Other**
- [Bootstrap Responsive breakpoints](http://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints)
- [Responsive Typography With Sass Maps](https://www.smashingmagazine.com/2015/06/responsive-typography-with-sass-maps/)
