### ISSUE TITLE
Define color system

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#34]
**Description**
Design color system

**Tools**
- [Palx base #005bf7](https://palx.jxnblk.com/005bf7)
- [Colorable (#181b22)](https://colorable.jxnblk.com/ffffff/181b22)
- [Monochrome](https://monochrome.jxnblk.com/)
- [Coolors](https://coolors.co/2c3240-8f98ad-d3d8e4-ef233c-d90429)

**Tasks**
- [x] Define primary / base color
- [x] Define white color
- [x] Define black color
- [x] Define electric-blue color
- [x] Define electric-magenta color
- [x] Define success-green color
- [x] Define danger-red color
- [x] Define warning-yellow color
- [x] Define info-blue color
- [x] Define gray color set
- [x] Define midnight color set
- [x] Define deep-slate color set
- [x] Define blue-gray color set
- [x] Define blue color set
- [x] Define indigo color set
- [x] Define violet color set
- [x] Define fuschia color set
- [x] Define pink color set
- [x] Define red color set
- [x] Define orange color set
- [x] Define yellow color set
- [x] Define lime color set
- [x] Define green color set
- [x] Define teal color set
- [x] Define cyan color set
- [x] Define alternative color set

Next
- [#35 Add color system to Meta Global Sketch library](https://github.com/universelabs/meta/issues/35)
- [#36 Add Sass color system to Meta](https://github.com/universelabs/meta/issues/36)

**External references**
- Material Design Color – https://material.io/design/color/
- Color Tool – [Coolors.co - The super fast color schemes generator (coolors.co)](https://coolors.co/)
- Color Tool – [0to255 - Color tool that helps web designers find variations of any color (0to255.com)](http://www.0to255.com/)
- Color Tool – [Material UI Color Tool](https://material.io/tools/color/#!/?view.left=0&view.right=0)
- Color Tool – [Material UI Colors (materialuicolors.co)](http://materialuicolors.co/)
- Color Gradients – [WebGradients.com (webgradients.com)](https://webgradients.com/)
- Color Gradients – [Grabient (grabient.com)](https://www.grabient.com/)
- Color Gradients – [Easing Gradients](https://larsenwork.com/easing-gradients/)
- Color Systems – [Designing Systematic Colors](https://uxplanet.org/designing-systematic-colors-b5d2605b15c)
- Color Accessibility – [Accessible color palette builder](https://toolness.github.io/accessible-color-matrix/)
- Color Accessibility – [Color Contrast Crash Course for Interface Design](https://medium.com/@mds/color-contrast-crash-course-for-interface-design-a69c987abe1b)
- Color Article – [It’s Only Color](https://robots.thoughtbot.com/Its-only-color)

**Comment by guylepage3** [comment]
```
//
// Color system
//

$gray-50:  #FAFAFA;
$gray-100: #F5F5F5;
$gray-200: #EEEEEE;
$gray-300: #E0E0E0;
$gray-400: #BDBDBD;
$gray-500: #9E9E9E;
$gray-600: #757575;
$gray-700: #616161;
$gray-800: #424242;
$gray-900: #212121;

$grays: (); // !default
// stylelint-disable-next-line scss/dollar-variable-default
$grays: map-merge(
  (
    "50":  $gray-50,
    "100": $gray-100,
    "200": $gray-200,
    "300": $gray-300,
    "400": $gray-400,
    "500": $gray-500,
    "600": $gray-600,
    "700": $gray-700,
    "800": $gray-800,
    "900": $gray-900
  ),
  $grays
);

$base: #005bf7;
$white:    #fff;    // !default
$black:    #000;    // !default

$success-green:    #00BB00;
$danger-red:       #FF0000;
$warning-yellow:   #FBC02D;
$info-blue:        #1E90FF;

$midnight-50:  #;
$midnight-100: #;
$midnight-200: #;
$midnight-300: #;
$midnight-400: #;
$midnight-500: #;
$midnight-600: #;
$midnight-700: #;
$midnight-800: #;
$midnight-900: #;

$deep-slate-50:  #;
$deep-slate-100; #;
$deep-slate-200; #;
$deep-slate-300; #;
$deep-slate-400; #;
$deep-slate-500; #;
$deep-slate-600; #;
$deep-slate-700; #;
$deep-slate-800; #;
$deep-slate-900; #;

$blue-gray-50:  #f8f9fa;
$blue-gray-100: #ecedf0;
$blue-gray-200: #dee0e5;
$blue-gray-300: #cfd3d9;
$blue-gray-400: #bfc4cc;
$blue-gray-500: #adb3be;
$blue-gray-600: #98a0ae;
$blue-gray-700: #80899a;
$blue-gray-800: #626c7e;
$blue-gray-900: #393f4a;

$blue-50:  #e5effe;
$blue-100: #c9ddfd;
$blue-200: #a9c9fc;
$blue-300: #82b1fb;
$blue-400: #5091f9;
$blue-500: #005ff7;
$blue-600: #0055de;
$blue-700: #004ac2;
$blue-800: #003da0;
$blue-900: #002b71;

$indigo-50:  #edeafe;
$indigo-100: #d8d4fd;
$indigo-200: #c1b9fc;
$indigo-300: #a599fb;
$indigo-400: #7e6dfa;
$indigo-500: #1d00f7;
$indigo-600: #1a00df;
$indigo-700: #1700c4;
$indigo-800: #1300a3;
$indigo-900: #0d0075;

$violet-50:  #f6e9fe;
$violet-100: #ecd1fd;
$violet-200: #e1b6fc;
$violet-300: #d394fb;
$violet-400: #c166fa;
$violet-500: #9800f7;
$violet-600: #8900df;
$violet-700: #7800c4;
$violet-800: #6400a2;
$violet-900: #480075;

$fuschia-50:  #feeafc;
$fuschia-100: #fdd4f8;
$fuschia-200: #fcb9f4;
$fuschia-300: #fb99f0;
$fuschia-400: #fa6de9;
$fuschia-500: #f700da;
$fuschia-600: #df00c5;
$fuschia-700: #c400ad;
$fuschia-800: #a40090;
$fuschia-900: #770069;

$pink-50:  #feeaf2;
$pink-100: #fdd3e3;
$pink-200: #fcb9d3;
$pink-300: #fb98be;
$pink-400: #fa6ca2;
$pink-500: #f7005f;
$pink-600: #df0056;
$pink-700: #c4004b;
$pink-800: #a3003f;
$pink-900: #77002d;

$red-50:  #feebe9;
$red-100: #fdd5d0;
$red-200: #fcbcb4;
$red-300: #fb9d91;
$red-400: #fa7462;
$red-500: #f71d00;
$red-600: #df1a00;
$red-700: #c41700;
$red-800: #a31300;
$red-900: #750d00;

$orange-50:  #fef2e0;
$orange-100: #fce5be;
$orange-200: #fbd699;
$orange-300: #fac46f;
$orange-400: #f8b03d;
$orange-500: #f79800;
$orange-600: #df8900;
$orange-700: #c47800;
$orange-800: #a26400;
$orange-900: #754800;

$yellow-50:  #fafee2;
$yellow-100: #f6fdc1;
$yellow-200: #f0fb9d;
$yellow-300: #eafa73;
$yellow-400: #e3f940;
$yellow-500: #daf700;
$yellow-600: #c5df00;
$yellow-700: #adc400;
$yellow-800: #90a400;
$yellow-900: #697700;

$lime-50:  #eefee4;
$lime-100: #dbfdc6;
$lime-200: #c6fca4;
$lime-300: #adfa7c;
$lime-400: #8df949;
$lime-500: #5ff700;
$lime-600: #56df00;
$lime-700: #4bc400;
$lime-800: #3fa300;
$lime-900: #2d7700;

$green-50:  #e9feeb;
$green-100: #d0fdd5;
$green-200: #b3fcbc;
$green-300: #90fb9d;
$green-400: #60fa72;
$green-500: #00f71d;
$green-600: #00df1a;
$green-700: #00c417;
$green-800: #00a413;
$green-900: #00770e;

$teal-50:  #e7fef5;
$teal-100: #cdfdeb;
$teal-200: #affcde;
$teal-300: #8afbcf;
$teal-400: #58f9bb;
$teal-500: #00f798;
$teal-600: #00df89;
$teal-700: #00c479;
$teal-800: #00a464;
$teal-900: #007749;

$cyan-50:  #e4fbfe;
$cyan-100: #c6f6fd;
$cyan-200: #a4f1fc;
$cyan-300: #7cecfa;
$cyan-400: #48e4f9;
$cyan-500: #00daf7;
$cyan-600: #00c5df;
$cyan-700: #00adc4;
$cyan-800: #0090a3;
$cyan-900: #006876

$alt-red-500:          #F44336; // Material Red 500
$alt-red-600:          #E53935; // Material Red 600
$alt-pink-500:         #E91E63; // Material Pink 500
$alt-pink-600:         #D81B60; // Material Pink 600
$alt-purple-500:       #9C27B0; // Material Purple 500
$alt-purple-600:       #8E24AA; // Material Purple 600
$alt-deep-purple-500:  #673AB7; // Material Deep Purple 500
$alt-deep-purple-600:  #5E35B1; // Material Deep Purple 600
$alt-indigo-500:       #3F51B5; // Material Indigo 500
$alt-indigo-600:       #3949AB; // Material Indigo 600
$alt-blue-500:         #2196F3; // Material Blue 500
$alt-blue-600:         #1E88E5; // Material Blue 600
$alt-light-blue-500:   #03A9F4; // Material Light Blue 500
$alt-light-blue-600:   #039BE5; // Material Light Blue 600
$alt-cyan-500:         #00BCD4; // Material Cyan 500
$alt-cyan-600:         #00ACC1; // Material Cyan 600
$alt-teal-500:         #009688; // Material Teal 500
$alt-teal-600:         #00897B; // Material Teal 600
$alt-green-500:        #4CAF50; // Material Green 500
$alt-green-600:        #43A047; // Material Green 600
$alt-light-green-500:  #8BC34A; // Material Light Green 500
$alt-light-green-600:  #7CB342; // Material Light Green 600
$alt-lime-500:         #CDDC39; // Material Lime 500
$alt-lime-600:         #C0CA33; // Material Lime 600
$alt-yellow-500:       #FFEB3B; // Material Yellow 500
$alt-yellow-600:       #FDD835; // Material Yellow 600
$alt-amber-500:        #FFC107; // Material Amber 500
$alt-amber-600:        #FFB300; // Material Amber 600
$alt-orange-500:       #FF9800; // Material Orange 500
$alt-orange-600:       #FB8C00; // Material Orange 600
$alt-deep-orange-500:  #FF5722; // Material Deep Orange 500
$alt-deep-orange-600:  #F4511E; // Material Deep Orange 600
$alt-brown-500:        #795548; // Material Brown 500
$alt-brown-600:        #6D4C41; // Material Brown 600
$alt-blue-gray-500:    #607D8B; // Material Blue Gray 500
$alt-blue-gray-600:    #546E7A; // Material Blue Gray 600

$colors: (); // !default
// stylelint-disable-next-line scss/dollar-variable-default
$colors: map-merge(
  (
    "white":                  $white,
    "blck":                   $black,
    "success-green":          $success-green,
    "danger-red":             $danger-red,
    "warning-yellow":         $warning-yellow,
    "info-blue":              $info-blue,
    "midnight-50":            $midnight-50,
    "midnight-100":           $midnight-100,
    "midnight-200":           $midnight-200,
    "midnight-300":           $midnight-300,
    "midnight-400":           $midnight-400,
    "midnight-500":           $midnight-500,
    "midnight-600":           $midnight-600,
    "midnight-700":           $midnight-700,
    "midnight-800":           $midnight-800,
    "midnight-900":           $midnight-900,
    "deep-slate-50":          $deep-slate-50,
    "deep-slate-100":         $deep-slate-100,
    "deep-slate-200":         $deep-slate-200,
    "deep-slate-300":         $deep-slate-300,
    "deep-slate-400":         $deep-slate-400,
    "deep-slate-500":         $deep-slate-500,
    "deep-slate-600":         $deep-slate-600,
    "deep-slate-700":         $deep-slate-700,
    "deep-slate-800":         $deep-slate-800,
    "deep-slate-900":         $deep-slate-900,
    "blue-gray-50":           $blue-gray-50,
    "blue-gray-100":          $blue-gray-100,
    "blue-gray-200":          $blue-gray-200,
    "blue-gray-300":          $blue-gray-300,
    "blue-gray-400":          $blue-gray-400,
    "blue-gray-500":          $blue-gray-500,
    "blue-gray-600":          $blue-gray-600,
    "blue-gray-700":          $blue-gray-700,
    "blue-gray-800":          $blue-gray-800,
    "blue-gray-900":          $blue-gray-900,
    "blue-50":                $blue-50,
    "blue-100":               $blue-100,
    "blue-200":               $blue-200,
    "blue-300":               $blue-300,
    "blue-400":               $blue-400,
    "blue-500":               $blue-500,
    "blue-600":               $blue-600,
    "blue-700":               $blue-700,
    "blue-800":               $blue-800,
    "blue-900":               $blue-900,
    "indigo-50":              $indigo-50,
    "indigo-100":             $indigo-100,
    "indigo-200":             $indigo-200,
    "indigo-300":             $indigo-300,
    "indigo-400":             $indigo-400,
    "indigo-500":             $indigo-500,
    "indigo-600":             $indigo-600,
    "indigo-700":             $indigo-700,
    "indigo-800":             $indigo-800,
    "indigo-900":             $indigo-900,
    "violet-50":              $violet-50,
    "violet-100":             $violet-100,
    "violet-200":             $violet-200,
    "violet-300":             $violet-300,
    "violet-400":             $violet-400,
    "violet-500":             $violet-500,
    "violet-600":             $violet-600,
    "violet-700":             $violet-700,
    "violet-800":             $violet-800,
    "violet-900":             $violet-900,
    "fuschia-50":             $fuschia-50,
    "fuschia-100":            $fuschia-100,
    "fuschia-200":            $fuschia-200,
    "fuschia-300":            $fuschia-300,
    "fuschia-400":            $fuschia-400,
    "fuschia-500":            $fuschia-500,
    "fuschia-600":            $fuschia-600,
    "fuschia-700":            $fuschia-700,
    "fuschia-800":            $fuschia-800,
    "fuschia-900":            $fuschia-900,
    "pink-50":                $pink-50,
    "pink-100":               $pink-100,
    "pink-200":               $pink-200,
    "pink-300":               $pink-300,
    "pink-400":               $pink-400,
    "pink-500":               $pink-500,
    "pink-600":               $pink-600,
    "pink-700":               $pink-700,
    "pink-800":               $pink-800,
    "pink-900":               $pink-900,
    "red-50":                 $red-50,
    "red-100":                $red-100,
    "red-200":                $red-200,
    "red-300":                $red-300,
    "red-400":                $red-400,
    "red-500":                $red-500,
    "red-600":                $red-600,
    "red-700":                $red-700,
    "red-800":                $red-800,
    "red-900":                $red-900,
    "orange-50":              $orange-50,
    "orange-100":             $orange-100,
    "orange-200":             $orange-200,
    "orange-300":             $orange-300,
    "orange-400":             $orange-400,
    "orange-500":             $orange-500,
    "orange-600":             $orange-600,
    "orange-700":             $orange-700,
    "orange-800":             $orange-800,
    "orange-900":             $orange-900,
    "yellow-50":              $yellow-50,
    "yellow-100":             $yellow-100,
    "yellow-200":             $yellow-200,
    "yellow-300":             $yellow-300,
    "yellow-400":             $yellow-400,
    "yellow-500":             $yellow-500,
    "yellow-600":             $yellow-600,
    "yellow-700":             $yellow-700,
    "yellow-800":             $yellow-800,
    "yellow-900":             $yellow-900,
    "lime-50":                $lime-50,
    "lime-100":               $lime-100,
    "lime-200":               $lime-200,
    "lime-300":               $lime-300,
    "lime-400":               $lime-400,
    "lime-500":               $lime-500,
    "lime-600":               $lime-600,
    "lime-700":               $lime-700,
    "lime-800":               $lime-800,
    "lime-900":               $lime-900,
    "green-50":               $green-50,
    "green-100":              $green-100,
    "green-200":              $green-200,
    "green-300":              $green-300,
    "green-400":              $green-400,
    "green-500":              $green-500,
    "green-600":              $green-600,
    "green-700":              $green-700,
    "green-800":              $green-800,
    "green-900":              $green-900,
    "teal-50":                $teal-50,
    "teal-100":               $teal-100,
    "teal-200":               $teal-200,
    "teal-300":               $teal-300,
    "teal-400":               $teal-400,
    "teal-500":               $teal-500,
    "teal-600":               $teal-600,
    "teal-700":               $teal-700,
    "teal-800":               $teal-800,
    "teal-900":               $teal-900,
    "cyan-50":                $cyan-50,
    "cyan-100":               $cyan-100,
    "cyan-200":               $cyan-200,
    "cyan-300":               $cyan-300,
    "cyan-400":               $cyan-400,
    "cyan-500":               $cyan-500,
    "cyan-600":               $cyan-600,
    "cyan-700":               $cyan-700,
    "cyan-800":               $cyan-800,
    "cyan-900":               $cyan-900,
    "alt-red-500":            $alt-red-500,
    "alt-red-600":            $alt-red-600,
    "alt-pink-500":           $alt-pink-500,
    "alt-pink-600":           $alt-pink-600,
    "alt-purple-500":         $alt-purple-500,
    "alt-purple-600":         $alt-purple-600,
    "alt-deep-purple-500":    $alt-deep-purple-500,
    "alt-deep-purple-600":    $alt-deep-purple-600,
    "alt-indigo-500":         $alt-indigo-500,
    "alt-indigo-600":         $alt-indigo-600,
    "alt-blue-500":           $alt-blue-500,
    "alt-blue-600":           $alt-blue-600,
    "alt-light-blue-500":     $alt-light-blue-500,
    "alt-light-blue-600":     $alt-light-blue-600,
    "alt-cyan-500":           $alt-cyan-500,
    "alt-cyan-600":           $alt-cyan-600,
    "alt-teal-500":           $alt-teal-500,
    "alt-teal-600":           $alt-teal-600,
    "alt-green-500":          $alt-green-500,
    "alt-green-600":          $alt-green-600,
    "alt-light-green-500":    $alt-light-green-500,
    "alt-light-green-600":    $alt-light-green-600,
    "alt-lime-500":           $alt-lime-500,
    "alt-lime-600":           $alt-lime-600,
    "alt-yellow-500":         $alt-yellow-500,
    "alt-yellow-600":         $alt-yellow-600,
    "alt-amber-500":          $alt-amber-500,
    "alt-amber-600":          $alt-amber-600,
    "alt-orange-500":         $alt-orange-500,
    "alt-orange-600":         $alt-orange-600,
    "alt-deep-orange-500":    $alt-deep-orange-500,
    "alt-deep-orange-600":    $alt-deep-orange-600,
    "alt-brown-500":          $alt-brown-500,
    "alt-brown-600":          $alt-brown-600,
    "alt-blue-gray-500":      $alt-blue-gray-500,
    "alt-blue-gray-600":      $alt-blue-gray-600
  ),
  $colors
);

$primary:       $base;
$secondary:     $pink-500;
$success:       $success-green;
$info:          $info-blue;
$warning:       $warning-yellow;
$danger:        $danger-red;
$light:         $gray-100; // !default
$dark:          $gray-900; // !default

$theme-colors: (); // !default
// stylelint-disable-next-line scss/dollar-variable-default
$theme-colors: map-merge(
  (
    "primary":    $primary,
    "secondary":  $secondary,
    "success":    $success,
    "info":       $info,
    "warning":    $warning,
    "danger":     $danger,
    "light":      $light,
    "dark":       $dark
  ),
  $theme-colors
);

// Set a specific jump point for requesting color jumps
$theme-color-interval:      8%; // !default

// The yiq lightness value that determines when the lightness of color changes 
// from "dark" to "light". Acceptable values are between 0 and 255.
$yiq-contrasted-threshold:  150; // !default

// Customize the light and dark text colors for use in our YIQ color contrast 
// function.
$yiq-text-dark:             $gray-900; // !default
$yiq-text-light:            $white; // !default
```

**Comment by guylepage3** [comment]
Done
