### ISSUE TITLE
Create new "Meta Global" Sketch Library

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#35]
**Description**
Create new "Meta Global" Sketch Library.

A summary of the issue If suitable, include the tasks required for the issue.

**Tasks**
- [ ] Add all "Fill *" Color Layer Styles.
- [ ] Add all "Fill Border *" Color Layer Styles.
- [ ] Add all "Border *" Color Layer Styles.

**Comment by guylepage3** [comment]
<img width="1064" alt="screenshot 2019-01-11 15 23 36" src="https://user-images.githubusercontent.com/1711854/51057880-ef06af00-15b4-11e9-8d88-916e1985fa62.png">
