### ISSUE TITLE
Add Meta color system

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#36]
**Description**
Add [Meta color system](https://github.com/universelabs/meta/issues/34)

**Tasks**
- [x] Double check color system
- [x] Define color, gray and base Sass mapping
- [x] Add and test
