### ISSUE TITLE
Add Editorial Typography

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#41]
**Description**
Add Editorial Typography

As noted #13, we identified the need for two types of typography:
  1. **Regular Typography** for interface design and layout within graphical 
     user interfaces. ie. List of songs, play button, settings.
  2. **Editorial Typography** for lengthier content sets of copy that are for 
     written communications. ie. promotional pages, blog posts, documentation, etc.
 
**Tasks**
- [x] Build out headings type
- [x] Build out displays
- [x] Build out leads
- [x] Build out paragraph
- [x] Build out blockquotes
- [x] Test
- [x] Documentation
- [x] Deploy
- [x] Push new release

**Comment by guylepage3** [comment]
Done
