### ISSUE TITLE
Add difference between editorial and regular UI elements to documentation

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#59]
**Description**
Add difference between editorial and regular UI elements to documentation.

**Tasks**
- [ ] Create a quick diagram for documentation.
- [ ] Update description on documentation.
- [ ] Update on README.md.

**Current wording in documentation**
Meta features `*-editorial` classes for `headings`, `displays`, `leads` and `blockquotes`. The classes add additional `y` axis `margin` spacing, making them ideal for products looking for advanced typography, such as blogs, editorial sites, infographics, and more.

**Comment by guylepage3** [comment]
Issue is based upon feedback from @dantrevino

Dan [3:28 AM]
Applying meta-ui 'lead lead-editorial' to my navbar.  'lead' might not be the right class because of the large default top margin, but maybe you can suggest some options?
Peek 2019-03-25 00-25.gif 
![image](https://user-images.githubusercontent.com/1711854/54916203-6028e380-4ecf-11e9-96c5-cf6d5278741f.png)


Dan [3:28 AM]
loving the docs

Guy Lepage [7:01 AM]
Yes. The fix there is to use `regular` classes without the `*-editorial` class.

Guy Lepage [7:12 AM]
```Meta features `*-editorial` classes for `headings`, `displays`, `leads` and `blockquotes`. The classes add additional `y` axis `margin` spacing, making them ideal for products looking for advanced typography, such as blogs, editorial sites, infographics, and more.```
I need to reword this a bit.
To make it clearer to use `*-editorial` classes for blog, editorial content, etc. and the regular classes for UI.

Guy Lepage [7:19 AM]
So for your UI elements, as we see in your sidebar, I would use `<p class="lead">...</p>`
Does that make sense?
I’m creating a quick diagram for this and place it in the documentation for clarity.

**Comment by guylepage3** [comment]
Pushing to Sprint 2. Will do if there is time left over in sprint 2.
